const products = [
  {
    _id: '1',
    name: 'Airpods',
    image: '/images/airpods.jpg',
    description: 'Bluetooth headphones by Apple',
    brand: 'Apple',
    category: 'Electronics',
    price: 99.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Mouse',
    image: '/images/mouse.jpg',
    description: 'Bluetooth headphones by Apple',
    brand: 'Google',
    category: 'Electronics',
    price: 9.99,
    countInStock: 15,
    rating: 5,
    numReviews: 7,
  },
  {
    _id: '3',
    name: 'Phone',
    image: '/images/phone.jpg',
    description: 'Bluetooth headphones by Apple',
    brand: 'Apple',
    category: 'Electronics',
    price: 399.99,
    countInStock: 6,
    rating: 3.5,
    numReviews: 2,
  },
  {
    _id: '4',
    name: 'Alexa',
    image: '/images/alexa.jpg',
    description: 'A home smarter than you',
    brand: 'Amazon',
    category: 'Electronics',
    price: 49.99,
    countInStock: 0,
    rating: 3,
    numReviews: 87,
  },
  {
    _id: '5',
    name: 'Camera',
    image: '/images/camera.jpg',
    description: 'A cool camera',
    brand: 'Canon',
    category: 'Electronics',
    price: 399.99,
    countInStock: 6,
    rating: 4,
    numReviews: 14,
  },
  {
    _id: '6',
    name: 'Playstation',
    image: '/images/playstation.jpg',
    description: 'Do people have these still?',
    brand: 'Playstation',
    category: 'Electronics',
    price: 799.99,
    countInStock: 6,
    rating: 3,
    numReviews: 9,
  },
];

export default products;
